/**
 * Subscription API Endpoints
 * Centralized endpoint configuration for subscription feature
 */

export const SUBSCRIPTION_ENDPOINTS = {
  BASE: '/api/subscription',
  LIST: '/api/subscription/list',
  DETAILS: '/api/subscription/:id',
  CREATE: '/api/subscription/create',
  UPDATE: '/api/subscription/:id/update',
  CANCEL: '/api/subscription/:id/cancel',
  AVAILABLE_PLANS: '/available-plans',
  GET_SUBSCRIPTION_PLANS: '/subscription/getAllPlansWithPurchase',
  ELIGIBLE_COUPONS: '/coupon/eligibleCoupons',
  PREPARE_SUBSCRIPTION: '/subscription/prepare',
  CREATE_PAYMENT_ORDER: '/payment/create-order',
  VERIFY_PAYMENT: '/payment/verify',
  PAYMENT_FAILURE: '/payment/failure',
  SUMMARY_WITH_PLAN: '/subscription/summary-with-plan',
  UPDATE_ADDON: '/subscription/addon/update',
  MEMBERS_CALC_SUMMARY: '/subscription/members-calculations-summary',
};

// Flattened endpoints for easier access
export const SUBSCRIPTION_ENDPOINTS_FLAT = {
  BASE: SUBSCRIPTION_ENDPOINTS.BASE,
  LIST: SUBSCRIPTION_ENDPOINTS.LIST,
  DETAILS: SUBSCRIPTION_ENDPOINTS.DETAILS,
  CREATE: SUBSCRIPTION_ENDPOINTS.CREATE,
  UPDATE: SUBSCRIPTION_ENDPOINTS.UPDATE,
  CANCEL: SUBSCRIPTION_ENDPOINTS.CANCEL,
  AVAILABLE_PLANS: SUBSCRIPTION_ENDPOINTS.AVAILABLE_PLANS,
  GET_SUBSCRIPTION_PLANS: SUBSCRIPTION_ENDPOINTS.GET_SUBSCRIPTION_PLANS,
  ELIGIBLE_COUPONS: SUBSCRIPTION_ENDPOINTS.ELIGIBLE_COUPONS,
  PREPARE_SUBSCRIPTION: SUBSCRIPTION_ENDPOINTS.PREPARE_SUBSCRIPTION,
  CREATE_PAYMENT_ORDER: SUBSCRIPTION_ENDPOINTS.CREATE_PAYMENT_ORDER,
  VERIFY_PAYMENT: SUBSCRIPTION_ENDPOINTS.VERIFY_PAYMENT,
  PAYMENT_FAILURE: SUBSCRIPTION_ENDPOINTS.PAYMENT_FAILURE,
  SUMMARY_WITH_PLAN: SUBSCRIPTION_ENDPOINTS.SUMMARY_WITH_PLAN,
  UPDATE_ADDON: SUBSCRIPTION_ENDPOINTS.UPDATE_ADDON,
  MEMBERS_CALC_SUMMARY: SUBSCRIPTION_ENDPOINTS.MEMBERS_CALC_SUMMARY,
};

export default SUBSCRIPTION_ENDPOINTS_FLAT;

