/**
 * Project Reports Page
 * Displays list of reports for a specific project
 */

import { useState, useMemo, useEffect } from 'react';
import { useNavigate, useParams, useLocation } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import dayjs from 'dayjs';
import SearchBar from '../../../components/ui/SearchBar';
import Filter from '../../../components/ui/Filter';
import DatePicker from '../../../components/ui/DatePicker';
import PageHeader from '../../../components/layout/PageHeader';
import Loader from '../../../components/ui/Loader';
import { ReportCard } from '../components';
import { ROUTES, getRoute } from '../../../constants/routes';
import { useWorkspaceRole } from '../../dashboard/hooks';
import { useAuth } from '../../auth/store/authStore';
import { useDPRLogs } from '../hooks/useDPRLogs';
import addCircleIcon from '../../../assets/icons/Add Circle.svg';
import EmptyState from '../../../components/shared/EmptyState';
import EmptyStateSvg from '../../../assets/icons/EmptyState.svg';

export default function ProjectReports() {
  const { t } = useTranslation('dpr');
  const navigate = useNavigate();
  const { projectId } = useParams();
  const location = useLocation();
  const { selectedWorkspace } = useAuth();
  const projectName = location.state?.projectName || 'Project';
  const currentUserRole = useWorkspaceRole();

  const [searchQuery, setSearchQuery] = useState('');
  const [timeFilter, setTimeFilter] = useState('');
  const [selectedDate, setSelectedDate] = useState(null);
  const [tempDate, setTempDate] = useState(null);

  // Calculate date range based on filters
  const { startDate, endDate } = useMemo(() => {
    let start = null;
    let end = null;

    if (selectedDate) {
      const d = dayjs(selectedDate);
      if (d.isValid()) {
        const formatted = d.format('YYYY-MM-DD');
        start = formatted;
        end = formatted;
      }
    } else if (timeFilter) {
      const today = dayjs();
      end = today.format('YYYY-MM-DD');

      switch (timeFilter) {
        case 'today':
          start = end;
          break;
        case 'last_week':
          start = today.subtract(7, 'day').format('YYYY-MM-DD');
          break;
        case 'last_month':
          start = today.subtract(30, 'day').format('YYYY-MM-DD');
          break;
        case 'last_3_months':
          start = today.subtract(90, 'day').format('YYYY-MM-DD');
          break;
        default:
          start = null;
          end = null;
      }
    }

    return { startDate: start, endDate: end };
  }, [selectedDate, timeFilter]);

  const { logs, isLoading } = useDPRLogs({
    workspaceId: selectedWorkspace,
    projectId,
    startDate,
    endDate
  });

  // Check if user can add reports (builder role cannot add)
  const canAddReport = currentUserRole?.toLowerCase() !== 'builder';

  const TIME_OPTIONS = [
    { value: 'today', label: t('filter.today') },
    { value: 'last_week', label: t('filter.lastWeek') },
    { value: 'last_month', label: t('filter.lastMonth') },
    { value: 'last_3_months', label: t('filter.last3Months') },
  ];

  const handleReportClick = (report) => {
    navigate(
      getRoute(ROUTES.DPR.REPORT_DETAILS, { projectId, reportId: report.id }),
      {
        state: {
          report,
          projectName,
          projectId,
        },
      }
    );
  };

  const handleAddReport = () => {
    navigate(getRoute(ROUTES.DPR.ADD_REPORT, { projectId }), {
      state: {
        projectName,
        projectId,
      },
    });
  };

  // Filter reports locally based on search
  const filteredReports = useMemo(() => {
    return logs.filter((report) => {
      const searchText = searchQuery.toLowerCase();
      let title = report.title || report.description || report.metadata?.note || `Report - ${report.date || ''}`;

      if (title.toLowerCase().includes('auto-generated by cron job') && report.project?.name) {
        title = report.project.name;
      }

      return !searchQuery || title.toLowerCase().includes(searchText);
    });
  }, [logs, searchQuery]);

  return (
    <div>
      <div className="max-w-7xl mx-auto">
        {/* Header Section */}
        <div className="mb-6">
          <PageHeader title={projectName}
            showBackButton={true}
            backTo={ROUTES.DPR.LIST}
          >
            <div className="flex flex-col sm:flex-row sm:items-center sm:flex-wrap gap-3 flex-1 w-full lg:justify-end">
              <SearchBar
                placeholder={t('search.placeholder')}
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full sm:w-auto sm:min-w-[260px]"
              />

              <Filter
                options={TIME_OPTIONS}
                value={timeFilter}
                onChange={(val) => {
                  setTimeFilter(val);
                  if (val) {
                    setSelectedDate(null);
                    setTempDate(null);
                  }
                }}
                placeholder={t('filter.label')}
                className="w-full sm:w-[140px] flex-shrink-0"
              />

              <DatePicker
                value={tempDate}
                onChange={(val) => setTempDate(val)}
                onAccept={(val) => {
                  setSelectedDate(val);
                  setTempDate(val);
                  if (val) setTimeFilter('');
                }}
                onKeyDown={(e) => {
                  if (e.key === 'Enter') {
                    setSelectedDate(tempDate);
                    if (tempDate) setTimeFilter('');
                  }
                }}
                className="w-full sm:w-[180px] flex-shrink-0"
                placeholder="dd/mm/yyyy"
              />

              {/* {canAddReport && (
                <button
                  type="button"
                  onClick={handleAddReport}
                  className="flex items-center justify-center sm:justify-start gap-2 text-accent font-medium whitespace-normal sm:whitespace-nowrap flex-shrink-0 cursor-pointer hover:opacity-80 transition-opacity w-full sm:w-auto"
                >
                  <img
                    src={addCircleIcon}
                    alt="Add"
                    className="w-5 h-5 flex-shrink-0"
                  />
                  <span className="text-sm sm:text-base">{t('actions.addReport')}</span>
                </button>
              )} */}
            </div>
          </PageHeader>
        </div>

        {/* Reports List */}
        {isLoading ? (
          <div className="flex items-center justify-center py-20">
            <Loader size="lg" />
          </div>
        ) : (!selectedDate && !timeFilter && !searchQuery) ? (
          <EmptyState
            image={EmptyStateSvg}
            title={t('emptyState.noReports')}
            message={t('emptyState.getStarted')}
          />
        ) : filteredReports.length === 0 ? (
          <EmptyState
            image={EmptyStateSvg}
            title={t('emptyState.noReports')}
            message={t('emptyState.adjustSearch')}
          />
        ) : (
          <div className="grid grid-cols-1 gap-4">
            {filteredReports.map((report) => (
              <ReportCard
                key={report.id}
                report={report}
                onClick={() => handleReportClick(report)}
              />
            ))}
          </div>
        )}
      </div>
    </div>
  );
}

